<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" projectName="MavenApp" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite skipped="0" failed="2" name="iSuite Mobile – Applications Android sur Google Play" duration-ms="0" started-at="2018-03-06T22:42:23Z" finished-at="2018-03-06T22:42:23Z" passed="0">
    <groups>
    </groups>
    <test name="suite_w_test_a" duration-ms="0" started-at="2018-03-06T22:42:23Z" finished-at="2018-03-06T22:42:23Z">
      <class name="fis.ch.test.my_app_test.TestCaseA">
        <test-method status="FAIL" signature="B()[pri:0, instance:fis.ch.test.my_app_test.TestCaseA@77556fd]" name="B" duration-ms="0" started-at="2018-03-06T23:42:23Z" finished-at="2018-03-06T23:42:23Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at fis.ch.test.my_app_test.TestCaseA.B(TestCaseA.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at fis.ch.test.my_app_test.AppTest.runTestNgProgrammatically(AppTest.java:80)
	at fis.ch.test.my_app_test.AppTest.main(AppTest.java:24)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B -->
        <test-method status="FAIL" signature="A()[pri:0, instance:fis.ch.test.my_app_test.TestCaseA@77556fd]" name="A" duration-ms="0" started-at="2018-03-06T23:42:23Z" finished-at="2018-03-06T23:42:23Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at fis.ch.test.my_app_test.TestCaseA.A(TestCaseA.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at fis.ch.test.my_app_test.AppTest.runTestNgProgrammatically(AppTest.java:80)
	at fis.ch.test.my_app_test.AppTest.main(AppTest.java:24)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A -->
      </class> <!-- fis.ch.test.my_app_test.TestCaseA -->
    </test> <!-- suite_w_test_a -->
  </suite> <!-- iSuite Mobile – Applications Android sur Google Play -->
  <suite skipped="2" failed="0" name="Comptabilité en ligne et gestion iSuite expert : votre partenaire digital" duration-ms="15" started-at="2018-03-06T22:42:23Z" finished-at="2018-03-06T22:42:23Z" passed="0">
    <groups>
    </groups>
    <test name="suite_z_test_b" duration-ms="15" started-at="2018-03-06T22:42:23Z" finished-at="2018-03-06T22:42:23Z">
      <class name="fis.ch.test.my_app_test.TestCase">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:fis.ch.test.my_app_test.TestCase@1e81f4dc]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-03-06T23:42:23Z" finished-at="2018-03-06T23:42:23Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at fis.ch.test.my_app_test.TestCase.beforeTest(TestCase.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at fis.ch.test.my_app_test.AppTest.runTestNgProgrammatically(AppTest.java:80)
	at fis.ch.test.my_app_test.AppTest.main(AppTest.java:24)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="f()[pri:0, instance:fis.ch.test.my_app_test.TestCase@1e81f4dc]" name="f" duration-ms="0" started-at="2018-03-06T23:42:23Z" finished-at="2018-03-06T23:42:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="fn()[pri:0, instance:fis.ch.test.my_app_test.TestCase@1e81f4dc]" name="fn" duration-ms="0" started-at="2018-03-06T23:42:23Z" finished-at="2018-03-06T23:42:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fn -->
      </class> <!-- fis.ch.test.my_app_test.TestCase -->
    </test> <!-- suite_z_test_b -->
  </suite> <!-- Comptabilité en ligne et gestion iSuite expert : votre partenaire digital -->
</testng-results>
