<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62" started-at="2018-03-06T22:30:32Z" finished-at="2018-03-06T22:30:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62" started-at="2018-03-06T22:30:32Z" finished-at="2018-03-06T22:30:32Z">
      <class name="fis.ch.test.my_app_test.TestCase">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:fis.ch.test.my_app_test.TestCase@7ac7a4e4]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-03-06T23:30:32Z" finished-at="2018-03-06T23:30:32Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at fis.ch.test.my_app_test.TestCase.beforeTest(TestCase.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="f()[pri:0, instance:fis.ch.test.my_app_test.TestCase@7ac7a4e4]" name="f" duration-ms="15" started-at="2018-03-06T23:30:32Z" finished-at="2018-03-06T23:30:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="fn()[pri:0, instance:fis.ch.test.my_app_test.TestCase@7ac7a4e4]" name="fn" duration-ms="0" started-at="2018-03-06T23:30:32Z" finished-at="2018-03-06T23:30:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fn -->
      </class> <!-- fis.ch.test.my_app_test.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
